services:
  flask-app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      MONGODB_URI: "mongodb://mongo:27017/unovastra"

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
